apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ic23kyxz4-nodejs-gitops
  description: This is GitOps manifest for ic23kyxz4-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ic23kyxz4-nodejs
    backstage.io/kubernetes-id: ic23kyxz4-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: ic23kyxz4-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ic23kyxz4-nodejs
